name: law_union_client
description: Law Faculty Student Union — student app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
